config/routes.rb
Zeroprotocol::Application.routes.draw do
  resources :likes

  resources :comments

  resources :posts

  resources :subscriptions

  resources :users

  resources :channels

  resources :organisations

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :name, :organisation_id
  validates :name, :presence => true, :uniqueness => true
  validates :organisation_id, :presence => true
  belongs_to :organisation
  has_many :subscriptions
  has_many :users, :through => :subscriptions
  has_many :posts
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @channel }
      else
        format.html { render action: 'new' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :organisation_id)
    end
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :organisation_id %><br>
    <%= f.text_field :organisation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Organisation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.organisation %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @channel.organisation %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>