config/routes.rb
Zeroprotocol::Application.routes.draw do
  resources :likes

  resources :comments

  resources :posts

  resources :subscriptions

  resources :users

  resources :channels

  resources :organisations

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :user_id, :channel_id
  validates :user_id, :channel_id, :presence => true
  validates_uniqueness_of :user_id, :scope => :channel_id, :message => "User can subscribe to a channel only once!"
  belongs_to :user
  belongs_to :channel
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subscription }
      else
        format.html { render action: 'new' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:user_id, :channel_id)
    end
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br>
    <%= f.text_field :channel_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Channel</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.user %></td>
        <td><%= subscription.channel %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subscription.user %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @subscription.channel %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>